[package]
name = "mydia"
version = "0.1.0"
authors = ["admodev <admosdigital@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorful = "0.2.1"
clap = "2.33.3"
dialoguer = "0.7.1"
console = "0.13.0"
